#!/usr/bin/env bash
# Turn on Pipeline Intelligence (one-time, per machine).
#
# PI is off in the committed compose. This writes a gitignored
# docker-compose.override.yaml that enables it all at once: the feature flags, the
# Gemini project, and a mount of your Google credentials -- which can't be
# committed, since the server runs in a container (not on GCP) and can't find
# Application Default Credentials on its own.
#
# It does not start anything. Run ./demo.sh up (or start) afterward - demo.sh
# picks up the override automatically. Delete the override to turn PI back off.
# Safe to re-run.
set -euo pipefail
cd "$(dirname "$0")"   # repo root
SELF=selfhosted


ADC_DEFAULT="$HOME/.config/gcloud/application_default_credentials.json"
CREDS="${GEMINI_CREDENTIALS_FILE:-}"
if [ -n "$CREDS" ]; then
  echo "Using GEMINI_CREDENTIALS_FILE: $CREDS"
elif [ -f "$ADC_DEFAULT" ]; then
  CREDS="$ADC_DEFAULT"
  echo "Using existing gcloud ADC: $CREDS"
elif command -v gcloud >/dev/null 2>&1; then
  echo "No credentials found. Launching: gcloud auth application-default login"
  echo "(Log in with an account that has Vertex AI access to the Gemini project.)"
  gcloud auth application-default login
  CREDS="$ADC_DEFAULT"
else
  echo "ERROR: no Google credentials available. Do ONE of:"
  echo "  - install gcloud, then re-run this script (it will log you in), or"
  echo "  - export GEMINI_CREDENTIALS_FILE=/path/to/service-account.json and re-run."
  exit 1
fi
[ -f "$CREDS" ] || { echo "ERROR: credentials file not found: $CREDS"; exit 1; }

cat > "$SELF/docker-compose.override.yaml" <<EOF
# Generated by setup-pipeline-intelligence.sh -- gitignored, machine-specific.
# Turns Pipeline Intelligence ON (flags + Gemini project + credentials) all at
# once. demo.sh layers this on automatically. Delete it to turn PI back off.
# Point at your own project by setting GEMINI_PROJECT_ID in selfhosted/.env.
services:
  bindplane:
    volumes:
      - $CREDS:/etc/gcloud/adc.json:ro
    environment:
      BINDPLANE_FEATURES_OVERRIDES_PIPELINE_INTELLIGENCE: "true"
      BINDPLANE_FEATURES_OVERRIDES_PIPELINE_INTELLIGENCE_CHAT: "true"
      BINDPLANE_LLM_GEMINI_PROJECT_ID: \${GEMINI_PROJECT_ID:-iris-dev-351502}
      BINDPLANE_LLM_GEMINI_LOCATION: \${GEMINI_LOCATION:-global}
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/adc.json
EOF

echo "Wrote $SELF/docker-compose.override.yaml"
echo "Done. Now run ./demo.sh up (or ./demo.sh start) to apply."
